dist: xenial

language: go

env:
#  - GO111MODULE=on
  - GOFLAGS='-mod vendor'

go:
- "1.13.6"

sudo: false

# Skip the install step. Don't `go get` dependencies. Only build with the code
# in vendor/
install: false

# Don't email me the results of the test runs.
notifications:
  email: false

before_script:
#  - go install github.com/golangci/golangci-lint/cmd/golangci-lint

script:
#  - golangci-lint run       # run a bunch of code checkers/linters in parallel
#  - go mod init
  - GOOS=linux GOARCH=amd64 go build .  # Run all the tests with the race detector enabled

#install:
#  # Add Godeps dependencies to GOPATH and PATH
#  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
#  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"
